os: linux
dist: xenial

language: node_js

git:
  submodules: flase

branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_94d6c4c1e025_key -iv $encrypted_94d6c4c1e025_iv -in travis.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- npm install -g hexo
- npm install
- npm remove hexo-generator-index
# - npm install hexo-deployer-rsync --save
- npm install hexo-deployer-sftp --save

install:
- git checkout master

addons:
  ssh_known_hosts: suna.comp.nus.edu.sg

script:
- hexo generate && hexo deploy
