language: node_js

branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_94d6c4c1e025_key -iv $encrypted_94d6c4c1e025_iv -in travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- npm install -g hexo
- npm install

addons:
  ssh_known_hosts: suna.comp.nus.edu.sg:22

script:
- hexo generate && rsync -az -vv --delete -e public/ wangwei@suna.comp.nus.edu.sg:/home/w/wangwei/public_html
